name: "Release"

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    name: Deploy release
    runs-on: ubuntu-latest
    timeout-minutes: 120
    environment: production

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy data
        uses: ./.github/actions/deploy-data
        with:
          db_host: ${{ secrets.DB_HOST }}
          db_name: ${{ secrets.DB_NAME }}
          db_user: ${{ secrets.DB_USER }}
          db_password: ${{ secrets.DB_PASSWORD }}
          db_port: ${{ secrets.DB_PORT }}

      - name: Deploy app
        uses: ./.github/actions/deploy-app
        with:
          clever_token: ${{ secrets.CLEVER_TOKEN }}
          clever_secret: ${{ secrets.CLEVER_SECRET }}
          clever_app_id: ${{ secrets.CLEVER_APP_ID }}
